### ISSUE TITLE
Twitter API is not working!

### ISSUE THREAD

**Issue by dweep612** [dweep612/nameprufer-api#2]
Twitter API is not giving a proper response whether the username is available or not.

**Comment by murt202** [comment]
### What I understood
- The reason is that when you send a GET request to `https://twitter.com/:username` it responds with an Html page that states if the user exists or not instead of changing the status code.
- Another problem is that it has a script that detects if javascript can be supported and if it doesn't it will not render the page. So that is tricky as we can parse the Html search for the keywords.

I will look into it and fix this bug.

**Comment by dweep612** [comment]
Great!, I know that hack but I created this issue for the beginner to contribute.
And you did it.
I will review your pull request and merge it in sometime.
